### POST login
POST http://localhost:4000/api/auth
Content-Type: application/json

{
    "username": "johndoe11",
    "password": "12345678"
}

### GET login
GET http://localhost:4000/api/auth
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjE2ZDc5MmVkNGMxZGYyNGY1ZWE5NzYxIn0sImlhdCI6MTYzNDY2MjM3MSwiZXhwIjoxNjM1MDIyMzcxfQ.LQcDBl7JznepqG-qFrMKMn4gJQx-NpaKskW-RC9eKY8
