### GET all movies
GET http://localhost:4000/api/movies/all

### GET TOPLIST 
GET http://localhost:4000/api/movies/top

### GET movies for voting
GET http://localhost:4000/api/movies/voting/617025d509b2dcb45c4e9991
