### POST
POST http://localhost:4000/api/movies
Content-Type: application/json

{
    "tmdbId": "550"
}

### GET id
GET http://localhost:4000/api/movies/6164051ad61ea5d4d5514641

### GET all movies
GET http://localhost:4000/api/movies/all

### GET TOPLIST 
GET http://localhost:4000/api/movies/top

### GET movies for voting
GET http://localhost:4000/api/movies/voting/617025d509b2dcb45c4e9991

### PATCH
PATCH http://localhost:4000/api/movies/6164051ad61ea5d4d5514641
Content-Type: application/json

{
    "rating": 1500
}

### DELETE
DELETE  http://localhost:4000/api/movies/6164051ad61ea5d4d5514641
