### POST
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "username": "JohnDoe",
    "email": "johndoe@mail.com",
    "password": "notencrypted"
}

### GET id
GET http://localhost:4000/api/users/616af3051daf09784aaa3d08

### PATCH
PATCH http://localhost:4000/api/users/616af3051daf09784aaa3d08
Content-Type: application/json

{
    "password": "stillnotencrypted"
}

### DELETE
DELETE  http://localhost:4000/api/users/616af3051daf09784aaa3d08
