### POST
POST http://localhost:4000/api/votings
Content-Type: application/json

{
    "userId": "616af3051daf09784aaa3d08",
    "firstMovieId": "616ab7d37e37d660eaf06978",
    "secondMovieId": "616718501868bdbd7b3a27f1"
}

### GET id
GET http://localhost:4000/api/votings/616434434460437e09d856f9


### PATCH
PATCH http://localhost:4000/api/votings/61641035590a4e9c5c32203e
Content-Type: application/json

{
    "isCanceled": false,
    "firstMovieWon": true
}
