import * as AiIcons from 'react-icons/ai'

export const sideBarData = [
  {
    id: 0,
    title: 'Home',
    path: '/',
    icon: <AiIcons.AiFillHome />,
    showToLoggedIn: false,
    mustBeLoggedIn: false,
    mustBeAdmin: false,
  },
  {
    id: 1,
    title: 'Dashboard',
    path: '/dashboard',
    icon: <AiIcons.AiFillHome />,
    showToLoggedIn: true,
    mustBeLoggedIn: true,
    mustBeAdmin: false,
  },
  {
    id: 2,
    title: 'Voting',
    path: '/voting',
    icon: <AiIcons.AiFillStar />,
    showToLoggedIn: true,
    mustBeLoggedIn: true,
    mustBeAdmin: false,
  },
  {
    id: 3,
    title: 'Toplist',
    path: '/toplist',
    icon: <AiIcons.AiOutlineAreaChart />,
    showToLoggedIn: true,
    mustBeLoggedIn: false,
    mustBeAdmin: false,
  },
  {
    id: 4,
    title: 'Profile',
    path: '/profile',
    icon: <AiIcons.AiFillIdcard />,
    showToLoggedIn: true,
    mustBeLoggedIn: true,
    mustBeAdmin: false,
  },
  {
    id: 5,
    title: 'Login',
    path: '/login',
    icon: <AiIcons.AiOutlineLogin />,
    showToLoggedIn: false,
    mustBeLoggedIn: false,
    mustBeAdmin: false,
  },
  {
    id: 6,
    title: 'Register',
    path: '/register',
    icon: <AiIcons.AiFillPlayCircle />,
    showToLoggedIn: false,
    mustBeLoggedIn: false,
    mustBeAdmin: false,
  },
  {
    id: 7,
    title: 'Add New Movie',
    path: '/add-new-movie',
    icon: <AiIcons.AiFillPlusCircle />,
    showToLoggedIn: true,
    mustBeLoggedIn: true,
    mustBeAdmin: true,
  },
  {
    id: 8,
    title: 'Movie Overview',
    path: '/movie-overview',
    icon: <AiIcons.AiFillRead />,
    showToLoggedIn: true,
    mustBeLoggedIn: true,
    mustBeAdmin: true,
  },
  {
    id: 9,
    title: 'Logout',
    path: '/profile',
    icon: <AiIcons.AiOutlineLogout />,
    showToLoggedIn: true,
    mustBeLoggedIn: true,
    mustBeAdmin: false,
  },
]
