import * as AiIcons from 'react-icons/ai'

export const sideBarData = [
  {
    title: 'Home',
    path: '/',
    icon: <AiIcons.AiFillHome />,
    showToLoggedIn: false,
    mustBeLoggedIn: false,
    mustBeAdmin: false,
  },
  {
    title: 'Dashboard',
    path: '/dashboard',
    icon: <AiIcons.AiFillHome />,
    showToLoggedIn: true,
    mustBeLoggedIn: true,
    mustBeAdmin: false,
  },
  {
    title: 'Voting',
    path: '/voting',
    icon: <AiIcons.AiFillStar />,
    showToLoggedIn: true,
    mustBeLoggedIn: true,
    mustBeAdmin: false,
  },
  {
    title: 'Toplist',
    path: '/toplist',
    icon: <AiIcons.AiOutlineAreaChart />,
    showToLoggedIn: true,
    mustBeLoggedIn: false,
    mustBeAdmin: false,
  },
  {
    title: 'Profile',
    path: '/profile',
    icon: <AiIcons.AiFillIdcard />,
    showToLoggedIn: true,
    mustBeLoggedIn: true,
    mustBeAdmin: false,
  },
  {
    title: 'Login',
    path: '/login',
    icon: <AiIcons.AiOutlineLogin />,
    showToLoggedIn: false,
    mustBeLoggedIn: false,
    mustBeAdmin: false,
  },
  {
    title: 'Register',
    path: '/register',
    icon: <AiIcons.AiFillPlayCircle />,
    showToLoggedIn: false,
    mustBeLoggedIn: false,
    mustBeAdmin: false,
  },
  {
    title: 'Add New Movie',
    path: '/add-new-movie',
    icon: <AiIcons.AiFillPlusCircle />,
    showToLoggedIn: true,
    mustBeLoggedIn: true,
    mustBeAdmin: true,
  },
  {
    title: 'Movie Overview',
    path: '/movie-overview',
    icon: <AiIcons.AiFillRead />,
    showToLoggedIn: true,
    mustBeLoggedIn: true,
    mustBeAdmin: true,
  },
  {
    title: 'Logout',
    path: '/profile',
    icon: <AiIcons.AiOutlineLogout />,
    showToLoggedIn: true,
    mustBeLoggedIn: true,
    mustBeAdmin: false,
  },
]
